{% set version = "0.8.0" %}

package:
  name: huira
  version: {{ version }}

source:
  # For conda-forge submission, replace git_url/git_rev with the tarball:
  # Generate the hash with:
  #   curl -sL https://github.com/huira-render/huira/archive/v{{ version }}.tar.gz | openssl sha256
  # url: https://github.com/huira-render/huira/archive/v{{ version }}.tar.gz
  # sha256: <HASH>
  git_url: ../..
  git_rev: HEAD

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - python
    - assimp
    - cfitsio
    - cspice
    - embree3
    - fftw
    - gdal
    - glm
    - indicators
    - libcurl
    - libtiff
    - libpng
    - libjpeg-turbo
    - tbb-devel
  run:
    - python

test:
  imports:
    - huira
  commands:
    - python -c "from huira.rgb import Scene; print('Python bindings OK')"
    - huira --help
    - huira fetch-tycho2 --help
    - huira process-tycho2 --help
    - test -f $PREFIX/include/huira/huira.hpp                                    # [unix]
    - if not exist %LIBRARY_INC%\\huira\\huira.hpp exit 1                        # [win]
    - test -f $PREFIX/lib/cmake/huira/huiraConfig.cmake                          # [unix]
    - test -f $PREFIX/lib/cmake/huira/huiraTargets.cmake                         # [unix]
    - if not exist %LIBRARY_LIB%\\cmake\\huira\\huiraConfig.cmake exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\huira\\huiraTargets.cmake exit 1        # [win]
    - test -f $PREFIX/share/huira/data/kernels/lsk/naif0012.tls                  # [unix]
    - if not exist %LIBRARY_PREFIX%\\share\\huira\\data\\kernels\\lsk\\naif0012.tls exit 1  # [win]

about:
  home: https://www.huira.space
  license: MIT
  license_file: ../../LICENSE # Change for conda-forge submission to point to the LICENSE file in the tarball
  summary: Spectral renderer for space applications
  description: |
    Huira is a C++ library for ray tracing in space applications.

extra:
  recipe-maintainers:
    - crgnam
