package:
  name: huira
  version: 0.1.0.dev

source:
  git_url: ../..
  git_rev: HEAD

build:
  number: 0

requirements:
  build:
    # Compiler and build tools - conda-build resolves these per-platform
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - assimp =5.4.3         # Asset Importer (3d models)
    - catch2 =3.8.0         # Testing Framework
    - cfitsio =4.6.2        # FITS I/O
    - cspice =67            # NASA SPICE
    - embree3 =3.13.5       # Ray tracing Acceleration
    - fftw =3.3.10          # Fast Fourier Transform
    - gdal =3.10.0          # Geospatial Abstraction Library
    - glm =1.0.1            # Linear Algebra for Graphics
    - indicators =2.3       # Progress bars
    - libtiff =4.7.0        # TIFF I/O
    - plog =1.1.10          # Logging
    - tbb-devel =2021.12.0  # Intel TBB
    - termcolor-cpp =2.0.0  # Terminal colors
    - yaml-cpp =0.8.0       # YAML parser
  run:
    # For a header-only library, users need dev packages to compile against huira
    - assimp =5.4.3         # Asset Importer (3d models)
    - cfitsio =4.6.2        # FITS I/O
    - cspice =67            # NASA SPICE
    - embree3 =3.13.5       # Ray tracing Acceleration
    - fftw =3.3.10          # Fast Fourier Transform
    - gdal =3.10.0          # Geospatial Abstraction Library
    - glm =1.0.1            # Linear Algebra for Graphics
    - indicators =2.3       # Progress bars
    - libtiff =4.7.0        # TIFF I/O
    - plog =1.1.10          # Logging
    - tbb-devel =2021.12.0  # Intel TBB
    - termcolor-cpp =2.0.0  # Terminal colors
    - yaml-cpp =0.8.0       # YAML parser

test:
  commands:
    # Check headers are installed
    - test -f $PREFIX/include/huira/huira.hpp  # [unix]
    - if not exist %LIBRARY_INC%\\huira\\huira.hpp exit 1  # [win]
    # Check CMake config files are installed
    - test -f $PREFIX/lib/cmake/huira/huiraConfig.cmake  # [unix]
    - test -f $PREFIX/lib/cmake/huira/huiraTargets.cmake  # [unix]
    - if not exist %LIBRARY_LIB%\\cmake\\huira\\huiraConfig.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\huira\\huiraTargets.cmake exit 1  # [win]

about:
  home: https://www.huira.space
  license: MIT
  license_file: LICENSE
  summary: Spectral renderer for space applications
  description: |
    Huira is a C++ library for ray tracing in space applications.