name: 'CMake Configuration for Python Bindings'
description: 'Configure the CMake build system with conda toolchain and Python bindings enabled'

inputs:
  platform:
    description: 'Target platforms: linux, macos, and windows'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure CMake (Linux)
      if: inputs.platform == 'linux'
      shell: bash -el {0}
      run: |
        cmake -B build \
          -DCMAKE_TOOLCHAIN_FILE="${GITHUB_WORKSPACE}/cmake/conda-toolchain.cmake" \
          -DCMAKE_BUILD_TYPE=Release \
          -DHUIRA_PYTHON=ON \
          -DHUIRA_APPS=ON \
          -G Ninja

    - name: Configure CMake (macOS)
      if: inputs.platform == 'macos'
      shell: bash -el {0}
      run: |
        # Detect architecture and configure accordingly
        if [[ "$(uname -m)" == "arm64" ]]; then
          # ARM64: use conda ninja
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE="${GITHUB_WORKSPACE}/cmake/conda-toolchain.cmake" \
            -DCMAKE_BUILD_TYPE=Release \
            -DHUIRA_PYTHON=ON \
            -DHUIRA_APPS=ON \
            -G Ninja
        else
          # x86_64: explicitly specify system ninja path to avoid conda ninja
          SYSTEM_NINJA=$(which ninja)
          echo "Using system ninja at: $SYSTEM_NINJA"

          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE="${GITHUB_WORKSPACE}/cmake/conda-toolchain.cmake" \
            -DCMAKE_BUILD_TYPE=Release \
            -DHUIRA_PYTHON=ON \
            -DHUIRA_APPS=ON \
            -DCMAKE_MAKE_PROGRAM="$SYSTEM_NINJA" \
            -G Ninja
        fi

    - name: Configure CMake (Windows)
      if: inputs.platform == 'windows'
      shell: bash -el {0}
      run: |
        conda activate huira_env

        cmake -B build \
          -DCMAKE_TOOLCHAIN_FILE="${GITHUB_WORKSPACE}/cmake/conda-toolchain.cmake" \
          -DCMAKE_BUILD_TYPE=Release \
          -DHUIRA_PYTHON=ON \
          -DHUIRA_APPS=ON \
          -G "Visual Studio 17 2022" \
          -A x64
