name: huira_env
channels:
  - conda-forge
dependencies:
  - assimp=5.4.3         # Asset Importer (3d models)
  - cfitsio=4.6.2        # FITS I/O
  - cspice=67            # NASA SPICE 
  - embree3=3.13.5       # Ray tracing Acceleration
  - fftw=3.3.10          # Fast Fourier Transform
  - gdal=3.10.0          # Geospatial Abstraction Library
  - gtest=1.16.0         # Google Testing Framework
  - libtiff=4.7.0        # TIFF I/O
  - tbb-devel=2021.12.0  # Intel TBB (Threading)