name: 'CMake Configuration for Testing'
description: 'Configure the CMake build system with conda toolchain and coverage enabled (Linux only)'

inputs:
  platform:
    description: 'Target platforms: Linux, MacOS, and Windows'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure CMake (Linux)
      if: inputs.platform == 'linux'
      shell: bash -el {0}
      run: |
        cmake -B build \
          -DCMAKE_TOOLCHAIN_FILE="${GITHUB_WORKSPACE}/cmake/conda-toolchain.cmake" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DHUIRA_TESTS=ON \
          -DHUIRA_COVERAGE=ON \
          -G Ninja

    - name: Configure CMake (macOS)
      if: inputs.platform == 'macos'
      shell: bash -el {0}
      run: |
        cmake -B build \
          -DCMAKE_TOOLCHAIN_FILE="${GITHUB_WORKSPACE}/cmake/conda-toolchain.cmake" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DHUIRA_TESTS=ON \
          -G Ninja

    - name: Configure CMake (Windows)
      if: inputs.platform == 'windows'
      shell: cmd
      run: |
        call conda activate huira_env
        
        cmake -B build ^
          -DCMAKE_TOOLCHAIN_FILE="../cmake/conda-toolchain.cmake" ^
          -DHUIRA_TESTS=ON ^
          -G "Visual Studio 17 2022" ^
          -A x64
