name: huira_env
channels:
  - conda-forge
dependencies:
  - assimp         # Asset Importer (3d models)
  - catch2         # Testing Framework
  - cfitsio        # FITS I/O
  - cspice         # NASA SPICE 
  - embree         # Ray tracing Acceleration
  - fftw           # Fast Fourier Transform
  - gdal           # Geospatial Abstraction Library
  - glm            # Linear Algebra for Graphics
  - indicators     # Progress bars
  - libcurl        # URL Transfer Library
  - libtiff        # TIFF I/O
  - libpng         # PNG I/O
  - libjpeg-turbo  # JPEG I/O
  - tbb-devel      # Intel TBB
