"""
huira_spectral_ext.py
=====================
Sphinx extension that fans out "spectral template" .rst files into per-specialization
copies before the build starts.

Configuration (conf.py)
-----------------------
::

    extensions = ['huira_spectral_ext']

    # Required: list of fully-qualified module names
    spectral_submodules = ['huira.rgb', 'huira.visible8', 'huira.swir8']

    # Optional: human-readable labels (used as directory names and section titles).
    # Defaults to the last component of the module name, capitalised.
    spectral_submodule_labels = {
        'huira.rgb':      'RGB',
        'huira.visible8': 'Visible8',
        'huira.swir8':    'SWIR8',
    }

    # Required if your spectral/ dir is not at the root of your docs source.
    # Path relative to srcdir (i.e. relative to conf.py location).
    spectral_template_dir = 'api_reference/python_api/spectral'

    # Optional: where to write generated per-specialization directories.
    # Defaults to the *parent* of spectral_template_dir, so generated dirs
    # sit alongside spectral/ automatically.
    # spectral_output_dir = 'api_reference/python_api'

Directive usage in template .rst files
---------------------------------------
Replace ``.. autoclass::`` with ``.. autoclass-spectral::`` (no module prefix)::

    .. autoclass-spectral:: Scene
       :members:
       :undoc-members:

Replace ``.. toctree::`` with ``.. toctree-spectral::`` inside spectral/ index files::

    .. toctree-spectral::
       :maxdepth: 1

       scene
       scene_view

The spectral/ template directory is automatically added to Sphinx's
``exclude_patterns`` so the raw placeholder directives are never processed
directly by Sphinx.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from sphinx.application import Sphinx
from sphinx.util import logging

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Regex helpers
# ---------------------------------------------------------------------------

_AUTOCLASS_SPECTRAL_RE = re.compile(
    r"^\.\. autoclass-spectral::\s*(\S+)(.*?)(?=^\.\. |\Z)",
    re.MULTILINE | re.DOTALL,
)
_TOCTREE_SPECTRAL_RE = re.compile(
    r"^\.\. toctree-spectral::(.*?)(?=^\.\. |\Z)",
    re.MULTILINE | re.DOTALL,
)


def _submodule_label(module: str, label_map: dict[str, str]) -> str:
    if module in label_map:
        return label_map[module]
    return module.split(".")[-1].capitalize()


def _replace_autoclass_spectral(text: str, module: str) -> str:
    def _replace(m: re.Match) -> str:
        return f".. autoclass:: {module}.{m.group(1)}{m.group(2)}"
    return _AUTOCLASS_SPECTRAL_RE.sub(_replace, text)


def _replace_toctree_spectral(text: str) -> str:
    def _replace(m: re.Match) -> str:
        return f".. toctree::{m.group(1)}"
    return _TOCTREE_SPECTRAL_RE.sub(_replace, text)


def _process_file(src: Path, dst: Path, module: str) -> None:
    text = src.read_text(encoding="utf-8")
    text = _replace_autoclass_spectral(text, module)
    text = _replace_toctree_spectral(text)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(text, encoding="utf-8")


def _add_to_gitignore(docs_dir: Path, rel_paths: list[str]) -> None:
    gitignore = docs_dir / ".gitignore"
    existing: set[str] = set()
    if gitignore.exists():
        existing = set(gitignore.read_text(encoding="utf-8").splitlines())
    new_entries = [p + "/" for p in rel_paths if p + "/" not in existing]
    if new_entries:
        with gitignore.open("a", encoding="utf-8") as fh:
            fh.write("\n# Auto-generated by huira_spectral_ext\n")
            fh.write("\n".join(new_entries) + "\n")


# ---------------------------------------------------------------------------
# Main build-time logic
# ---------------------------------------------------------------------------

def _generate_spectral_docs(app: Sphinx) -> None:
    config = app.config
    src_dir = Path(app.srcdir)

    submodules: list[str] = getattr(config, "spectral_submodules", [])
    if not submodules:
        logger.warning("huira_spectral_ext: 'spectral_submodules' is empty; nothing to generate.")
        return

    label_map: dict[str, str] = getattr(config, "spectral_submodule_labels", {})
    template_dir_name: str = getattr(config, "spectral_template_dir", "spectral")
    template_dir = src_dir / template_dir_name

    if not template_dir.is_dir():
        logger.warning("huira_spectral_ext: template directory '%s' not found.", template_dir)
        return

    # Output base: explicit config, or parent of the template dir (so generated
    # dirs sit alongside spectral/).
    output_dir_cfg: str | None = getattr(config, "spectral_output_dir", None)
    output_base = src_dir / output_dir_cfg if output_dir_cfg else template_dir.parent

    labels = [_submodule_label(m, label_map) for m in submodules]

    # Exclude the raw spectral/ templates from Sphinx processing so that
    # autoclass-spectral:: directives are never seen by docutils directly.
    template_rel = str(template_dir.relative_to(src_dir))
    if template_rel not in app.config.exclude_patterns:
        app.config.exclude_patterns.append(template_rel)
        logger.info("huira_spectral_ext: excluded '%s' from Sphinx source scan.", template_rel)

    # Fan out each submodule
    for module, label in zip(submodules, labels):
        out_dir = output_base / label
        rel_out = out_dir.relative_to(src_dir)
        logger.info("huira_spectral_ext: generating %s -> %s/", module, rel_out)

        for tmpl_path in sorted(template_dir.rglob("*.rst")):
            rel = tmpl_path.relative_to(template_dir)
            _process_file(tmpl_path, out_dir / rel, module)

        # Auto-generate a top-level index.rst if the template dir didn't have one
        top_index = out_dir / "index.rst"
        if not top_index.exists():
            title = f"{label} Spectral Specialization"
            underline = "=" * len(title)
            sub_indices = sorted(
                p.relative_to(out_dir).with_suffix("")
                for p in out_dir.rglob("index.rst")
                if p != top_index
            )
            toctree_entries = "\n".join(f"   {p.as_posix()}" for p in sub_indices)
            top_index.write_text(
                f"{title}\n{underline}\n\n"
                f".. toctree::\n   :maxdepth: 2\n\n{toctree_entries}\n",
                encoding="utf-8",
            )

    # Update .gitignore with relative paths to generated dirs
    gitignore_entries = [
        str((output_base / label).relative_to(src_dir))
        for label in labels
    ]
    _add_to_gitignore(src_dir, gitignore_entries)


# ---------------------------------------------------------------------------
# Sphinx integration
# ---------------------------------------------------------------------------

def setup(app: Sphinx) -> dict[str, Any]:
    app.add_config_value("spectral_submodules", default=[], rebuild="env")
    app.add_config_value("spectral_submodule_labels", default={}, rebuild="env")
    app.add_config_value("spectral_template_dir", default="spectral", rebuild="env")
    app.add_config_value("spectral_output_dir", default=None, rebuild="env")

    app.connect("builder-inited", _generate_spectral_docs)

    return {
        "version": "0.2.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
