name: Linux Build

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-22.04 # Updated August 2025
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up build environment
      uses: ./.github/actions/setup
      with:
        platform: linux
    
    - name: Configure project
      uses: ./.github/actions/cmake-configure
      with:
        platform: linux
    
    - name: Build project
      uses: ./.github/actions/build
      with:
        platform: linux