name: MacOS x86 Build

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  macos-x86-build:
    runs-on: macos-13 # Intel-based runner (x86_64) Updated August 2025
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up build environment
      uses: ./.github/actions/setup
      with:
        platform: macos
    
    - name: Configure project
      uses: ./.github/actions/cmake-configure
      with:
        platform: macos
    
    - name: Build project
      uses: ./.github/actions/build
      with:
        platform: macos