name: Windows Build

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-2022 # Updated August 2025
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up build environment
      uses: ./.github/actions/setup
      with:
        platform: windows
    
    - name: Configure project
      uses: ./.github/actions/cmake-configure
      with:
        platform: windows
    
    - name: Build project
      uses: ./.github/actions/build
      with:
        platform: windows